FROM docker.io/library/python:3.14-slim

RUN apt-get update && \
	apt-get install -y \
	git \
	curl \
	&& rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip && \
	pip install grokmirror

WORKDIR /data
