FROM docker.io/library/debian:bullseye-slim
# FROM docker.io/library/debian:trixie-slim # failing in trixie

RUN apt-get update && \
	apt-get install -y \
	git \
	perl \
	sqlite3 \
	curl \
	make \
	build-essential \
	# xapian search
	xapian-omega \
	libsearch-xapian-perl

WORKDIR /public-inbox

# COPY . .
RUN git clone http://public-inbox.org/public-inbox.git .

RUN yes | ./install/deps.perl all

# RUN rm -rf /var/lib/apt/lists/*

# TODO: check if PERL_INLINE_DIRECTORY & TMPDIR can help speeding this up
RUN perl Makefile.PL && \
	make && \
	# make test && \
	# make check runs tests in parallel
	make check && \
	make install

