FROM docker.io/library/debian:bookworm-slim as base
# FROM docker.io/library/debian:trixie-slim # failing in trixie

RUN apt-get update && \
	apt-get install -y \
	git \
	perl \
	sqlite3 \
	curl \
	# xapian search
	xapian-omega \
	libsearch-xapian-perl \
	public-inbox \
	spamc

WORKDIR /data


